// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFz45BIjfRs9HOVOZBtrJO7X2sD-bP6oM',
    appId: '1:747122732277:web:7b3fd3cc80f356911be9bc',
    messagingSenderId: '747122732277',
    projectId: 'taskify-e8cd7',
    authDomain: 'taskify-e8cd7.firebaseapp.com',
    storageBucket: 'taskify-e8cd7.firebasestorage.app',
    measurementId: 'G-RZ189ETFCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3dhdioU7ZY2vk8TvsxKe-mFg1tHoeafc',
    appId: '1:747122732277:android:bfeb3237a012ac501be9bc',
    messagingSenderId: '747122732277',
    projectId: 'taskify-e8cd7',
    storageBucket: 'taskify-e8cd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNg3mpzlD231xXL2cou5RoVOpRzA0fOrU',
    appId: '1:747122732277:ios:39c954b896d3a54e1be9bc',
    messagingSenderId: '747122732277',
    projectId: 'taskify-e8cd7',
    storageBucket: 'taskify-e8cd7.firebasestorage.app',
    iosBundleId: 'com.example.taskify001',
  );

}